### ISSUE TITLE
csproj is not generated properly

### ISSUE THREAD

**Issue by pedramp20** [dansiegel/Prism-Templates#14]
I have generated a project using the following code on Windows:

```
dotnet new prismforms -id com.contoso.awesomeapp -di Unity -fr netstandard1.6 -mc -ios-secret 
     "{my ios secret}" -android-secret "{my android secret}" -data None
     -auth AADB2C -client-id "{my AADB2C application id}"
```

However, the csproj is not generated properly and it does not contain the item group defining embedded resources like:

` <EmbeddedResource Include="Views\MainPage.xaml">
Generator>MSBuild:UpdateDesignTimeXaml</Generator>
</EmbeddedResource>` 

As the result, the xaml.g.cs files are not being generated, when building the project and I get 

`The name 'InitializeComponent' does not exist in the current context`

Secrets.cs file is not generated automatically either.

**Comment by dansiegel** [comment]
Xamarin has kinda helped screw up the imports... I actually just pushed some changes that should fix that issue and should have the fix out shortly

As for the Secrets.cs not generating I've heard of the issue but need to be able to reproduce it so I can determine what is causing the issue. If you can replace the tasks in the `Directory.build.targets` with the following (close and reopen Visual Studio) and then Clean/Rebuild, the output would be helpful in trying to determine why it's not generating. You'll want to check the build output you should get some debugging information if something didn't exist that was supposed to.

```xml
  <Target Name="BuildHostSecrets">
    <PropertyGroup>
      <BuildHostScriptLocation Condition=" '$(BuildHostScriptLocation)'=='' ">$(SolutionDir)\BuildHostSecrets.ps1</BuildHostScriptLocation>
    </PropertyGroup>
    <Message Condition="!Exists('$(BuildHostScriptLocation)')" Text="Build Host Script Does Not Exist = '$(BuildHostScriptLocation)'">
    <Exec Command="$(PowerShellExe) -NonInteractive -ExecutionPolicy Unrestricted -Command &quot;&amp; { &amp;$(BuildHostScriptLocation) }&quot;"
          Condition=" Exists('$(BuildHostScriptLocation)') And Exists('$(PowerShellExe)') " />
  </Target>

  <Target Name="Secrets">
    <PropertyGroup>
      <SecretsScriptLocation Condition=" '$(SecretsScriptLocation)'=='' ">$(SolutionDir)\Secrets.ps1</SecretsScriptLocation>
    </PropertyGroup>
    <Message Condition="Exists('$(SecretsScriptLocation)')" Text="Secrets Script Does Exist = '$(SecretsScriptLocation)'">
    <Message Condition="Exists('$(PowerShellExe)')" Text="Power Shell Exe Does Exist = '$(PowerShellExe)'">
    <Message Condition="!Exists('$(SecretsScriptLocation)')" Text="Secrets Script Does Not Exist = '$(SecretsScriptLocation)'">
    <Message Condition="!Exists('$(PowerShellExe)')" Text="Power Shell Exe Does Not Exist = '$(PowerShellExe)'">
    <Exec Command="$(PowerShellExe) -NonInteractive -ExecutionPolicy Unrestricted -Command &quot;&amp; { &amp;$(SecretsScriptLocation) -RootNamespace &apos;$(RootNamespace)&apos; -ProjectPath &apos;$(ProjectDir)&apos; }&quot;"
          Condition=" Exists('$(SecretsScriptLocation)') And Exists('$(PowerShellExe)') " />
  </Target>
```

**Comment by dansiegel** [comment]
Also the second issue actually duplicates issue #11 so I am going to close this issue as resolved. Feel free to update that issue with any additional information you can so i can try to get you a fix.

**Comment by pedramp20** [comment]
@dansiegel Thank you for your quick response. Regarding the csproj issue, how shortly it will be fixed? I restored the packages using
`dotnet new -i "Prism.Forms.QuickstartTemplates::*"`
But the issue still persisted. 
I also replaced the task in the `Directory.build.targets` with the provided code. However, when I closed and reopened Visual studio, the project failed to load.

**Comment by dansiegel** [comment]
sorry did that real quick.. looks like I missed the closing.. just fix the Message tags so they end `/>` instead of `>`
I still need to do some basic validations so it won't get pushed to NuGet for a little bit...

**Comment by dansiegel** [comment]
also just noticed something that could be causing the issue... try updating `Directory.build.props` so that the PowerShell path starts with `SystemRoot` instead of `WINDIR` and please let me know if that resolves the issue.

**Comment by pedramp20** [comment]
@dansiegel  I don't think that the powershell scripts are executed at all. I am not sure, but I think the scripts are skipped, because the build process is interrupted due to the errors that I explained. How can I make sure that the scripts are being executed?

**Comment by dansiegel** [comment]
As you will notice from issue 15, I will be deprecating the use of the PowerShell scripts as they are causing more problems then they are solving at the moment. I will try to have an update out later this week and it will probably be in the form of a NuGet that you will be able to add to your project. As for the build issues I have verified some the fixes for that and will have an updated package out in a few hours.

**Comment by pedramp20** [comment]
Thank you @dansiegel for creating such amazing templates. They saved me a lot of time and effort. I really appreciate it. The csproj issue is resolved. However, the Secrets.cs generation issue is still there and I am looking forward to your future update. for now I am creating the file manually.
I also faced a very small issue that I would like to report. `using Android.App;` is missing on top of AndroidInitializer.cs. 
Thank you again for your effort and quick responses.

**Comment by dansiegel** [comment]
my pleasure.. if you could please create a new issue and describe what the problem is with the `using Android.App` and what the steps are to reproduce. Thanks.

**Comment by dansiegel** [comment]
I've published a number of updates including a fix for the Secrets on Windows. Please give it a try and let me know how it works for you.

**Comment by lhughey** [comment]
I'm going to open a issue for the item you referenced  above in in [response 5](https://github.com/dansiegel/Prism-Templates/issues/14#issuecomment-333751583) about adding the closing tag in the Directory.build.targets file, so it can be on your list the next time you make an edit.  The suggested fix you mentioned works.  Thanks again for these great templates.

**Comment by dansiegel** [comment]
@lhughey that issue should be fixed in the current release
